# gitea/values-prod.yaml
persistence:
  enabled: true
  size: 20Gi
  accessModes:
    - ReadWriteOnce
  storageClass: "standard"

gitea:
  admin:
    username: admin
    password: "Pass@12345"
    email: "admin@dearjay22-gitea.k3p.dev"

  config:
    database:
      DB_TYPE: mysql
      HOST: "gitea-mysql.default.svc.cluster.local:3306"
      NAME: gitea
      USER: gitea
      PASSWD: gitea_pass
      SSL_MODE: disable

    server:
      ROOT_URL: "https://dearjay22-gitea.k3p.dev/"
      DOMAIN: "dearjay22-gitea.k3p.dev"
      SSH_DOMAIN: "dearjay22-gitea.k3p.dev"
      HTTP_PORT: 3000
      SSH_PORT: 22

    service:
      DISABLE_REGISTRATION: true

service:
  http:
    type: ClusterIP
    port: 3000

ssh:
  enabled: true
  service:
    type: ClusterIP
    port: 22
